iris.features.optional=ENTITY_TRANSLUCENT

screen=TARGET_FPS DEBUG_VIEW
sliders=TARGET_FPS

blend.gbuffers_textured_lit.colortex1=off
blend.gbuffers_terrain.colortex1=off
blend.gbuffers_terrain_solid.colortex1=off
blend.gbuffers_terrain_cutout.colortex1=off
blend.gbuffers_entities.colortex1=off
blend.gbuffers_block.colortex1=off
